### ISSUE TITLE
1.9.21 breaks loading files with stripped Unity version

### ISSUE THREAD

**Issue by erikchan002** [K0lb3/UnityPy#158]
**Code**
```python
import UnityPy
UnityPy.config.FALLBACK_UNITY_VERSION = "2020.3.32f1" 
env = UnityPy.load("res001_no001.zip")
```

**Error**
```
Error loading, reverting to EndianBinaryReader:
 'NoneType' object has no attribute 'groups'
```

**Bug**
This is a regression caused by #157 and does not happen with UnityPy 1.9.20
https://github.com/K0lb3/UnityPy/blob/b7d9f7793bbc34ae6da23ae326e427e6cd48484c/UnityPy/files/BundleFile.py#L95

**To Reproduce**
- a copy of the file that causes the problem
  - [res001_no001.zip](https://github.com/K0lb3/UnityPy/files/10081592/res001_no001.zip)
- following data:
  - Python version 3.10.8
  - UnityPy version 1.9.21

**Comment by K0lb3** [comment]
Thanks for reporting the issue.

The encryption handling for the CN version added version handling to the BundleFile,
which conflicted with the missing version at that point.
So, the handling for this case simply had to be ported from the SerializedFile.
