### ISSUE TITLE
`'FakeNode' object has no attribute 'type'`

### ISSUE THREAD

**Issue by RaenonX** [K0lb3/UnityPy#72]
### Code

```python
import UnityPy

def main():
    asset = UnityPy.load("assetbundle.manifest.decrypted")
    asset.objects[0].read()

if __name__ == '__main__':
    main()
```

### Error

```
E:\Personal@SSD\Game\DL\dragalia-asset-downloader-2\venv\Scripts\python.exe E:/Personal@SSD/Game/DL/dragalia-asset-downloader-2/sandbox.py
Traceback (most recent call last):
  File "E:\Personal@SSD\Game\DL\dragalia-asset-downloader-2\sandbox.py", line 10, in <module>
    main()
  File "E:\Personal@SSD\Game\DL\dragalia-asset-downloader-2\sandbox.py", line 6, in main
    asset.objects[0].read()
  File "E:\Personal@SSD\Game\DL\dragalia-asset-downloader-2\venv\lib\site-packages\UnityPy\files\ObjectReader.py", line 155, in read
    raise e
  File "E:\Personal@SSD\Game\DL\dragalia-asset-downloader-2\venv\lib\site-packages\UnityPy\files\ObjectReader.py", line 153, in read
    obj = getattr(classes, self.type.name, classes.Object)(self)
  File "E:\Personal@SSD\Game\DL\dragalia-asset-downloader-2\venv\lib\site-packages\UnityPy\classes\MonoBehaviour.py", line 15, in __init__
    self.read_typetree()
  File "E:\Personal@SSD\Game\DL\dragalia-asset-downloader-2\venv\lib\site-packages\UnityPy\classes\Object.py", line 50, in read_typetree
    tree = self.reader.read_typetree(nodes)
  File "E:\Personal@SSD\Game\DL\dragalia-asset-downloader-2\venv\lib\site-packages\UnityPy\files\ObjectReader.py", line 207, in read_typetree
    tree = TypeTreeHelper.read_typetree(
  File "E:\Personal@SSD\Game\DL\dragalia-asset-downloader-2\venv\lib\site-packages\UnityPy\helpers\TypeTreeHelper.py", line 78, in read_typetree
    obj[node.name] = read_value(nodes, reader, i)
  File "E:\Personal@SSD\Game\DL\dragalia-asset-downloader-2\venv\lib\site-packages\UnityPy\helpers\TypeTreeHelper.py", line 91, in read_value
    typ = node.type
AttributeError: 'FakeNode' object has no attribute 'type'
```

### Bug

Error shouldn't occur.

### Reproduce

File that causes the error: [assetbundle.manifest.zip](https://github.com/K0lb3/UnityPy/files/7344140/assetbundle.manifest.zip)

Python version: v3.9.5
UnityPy version: v1.7.14

Confirmed that the error only occurs after updating to v1.7.14. v1.7.11 - v1.7.13 doesn't have this issue.

**Comment by K0lb3** [comment]
Thanks for the report.
The issue was caused by the latest merged pull request,
which handled an inheritance from the dict class in a wrong way.

b7d2c153b7c4c5fe931452ccf33ed849fe64f8f7 fixes the issue.
